In [182]:
import numpy as np

In [183]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


1. How many negative numbers are there?



In [190]:
negatives = a[a < 0]
print(negatives)
len(negatives)

[-2 -1 -6 -7]


4

2. How many positive numbers are there?



In [191]:
positives = a[a > 0]
print(positives)
len(positives)

[ 4 10 12 23  3]


5

3. How many even positive numbers are there?



In [203]:
is_pos_mask = a > 0
positives = a[is_pos_mask]
is_even_mask = positives % 2 == 0
pos_evens = positives[is_even_mask]
print(pos_evens)
len(pos_evens)

[ 4 10 12]


3

In [207]:
# np.logical_and method
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
even_and_positive = np.logical_and(a > 0, a % 2 == 0)
print(a[even_and_positive])
len(a[even_and_positive])

[ 4 10 12]


3

4. If you were to add 3 to each data point, how many positive numbers would there be?



In [210]:
a += 3
my_array = a[a > 0]
print(my_array)
len(my_array)

[ 7 13 15 26  1  2  3  3  3  6]


10

In [199]:
#The same using a mask
mask = a > 0
pos_plus_3 = a[mask] + 3
print(pos_plus_3)
print(len(pos_plus_3))

[ 7 13 15 26  6]
5


5. If you squared each number, what would the new mean and standard deviation be?



In [31]:
sq_array = a ** 2
sq_array
print("sq_array = {}".format(sq_array))
sq_array.mean()
print("mean of sq_array = {}".format(sq_array.mean()))
sq_array.std()
print("standard deviation of sq_array = {}".format(sq_array.std()))

sq_array = [ 16 100 144 529   4   1   0   0   0  36   9  49]
mean of sq_array = 74.0
standard deviation of sq_array = 144.0243035046516


6. A common statistical operation on a dataset is centering. This means to adjust the data such that the center of the data is at 0. This is done by subtracting the mean from each data point. Center the data set.



In [35]:
mean = a.mean()
print(a.mean())
centered_set = a - mean
print(centered_set)

3.0
[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


7. Calculate the z-score for each data point. Recall that the z-score is given by: 

z-score = x - mean / std



In [213]:
mean = a.mean()
print(mean)
stdev = a.std()
print(stdev)
print("\n")
z_score = (a - mean) / stdev
print("The z_scores for array a:")
print((z_score))

6.0
8.06225774829855


The z_scores for array a:
[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


### More Numpy Practice...

### Setup 1:

In [71]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
my_a = np.array(a)

Use python's built in functionality/operators to determine the following:

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list


In [72]:
sum_of_a = my_a.sum()
print(sum_of_a)

55


Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list


In [73]:
min_of_a = my_a.min()
print(min_of_a)

1


Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [74]:
max_of_a = my_a.max()
print(max_of_a)

10


Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list


In [75]:
mean_of_a = my_a.mean()
print(mean_of_a)

5.5


Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together


In [78]:
product_of_a = np.prod(my_a)
print(product_of_a)

3628800


Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]


In [77]:
squares_of_a = my_a ** my_a
print(squares_of_a)

[          1           4          27         256        3125       46656
      823543    16777216   387420489 10000000000]


Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers


In [79]:
odds_in_a = my_a[my_a % 2 != 0]
print(odds_in_a)

[1 3 5 7 9]


Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [92]:
evens_in_a = my_a[my_a % 2 == 0]
print(evens_in_a)

[ 2  4  6  8 10]


What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...


### Setup 2: 

Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.


In [81]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]
my_b = np.array(b)

Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**


In [47]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)


In [83]:
sum_of_b = my_b.sum()
print(sum_of_b)

33


Exercise 2 - refactor the following to use numpy. 


In [48]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  


In [84]:
min_of_b = my_b.min()
print(min_of_b)

3


Exercise 3 - refactor the following maximum calculation to find the answer with numpy.


In [49]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


In [85]:
max_of_b = my_b.max()
print(max_of_b)

8


Exercise 4 - refactor the following using numpy to find the mean of b


In [ ]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len([b[0]]) + len(b[1]))


In [86]:
mean_of_b = my_b.mean()
print(mean_of_b)

5.5


Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.


In [50]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [87]:
product_of_b = np.prod(my_b)
print(product_of_b)

20160


Exercise 6 - refactor the following to use numpy to find the list of squares 


In [51]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [89]:
squares_of_b = my_b ** 2
print(squares_of_b)

[[ 9 16 25]
 [36 49 64]]


Exercise 7 - refactor using numpy to determine the odds_in_b


In [52]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [94]:
odds_in_b = my_b[my_b % 2 != 0]
print(odds_in_b)

[3 5 7]


Exercise 8 - refactor the following to use numpy to filter only the even numbers


In [53]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [95]:
evens_in_b = my_b[my_b % 2 == 0]
print(evens_in_b)

[4 6 8]


Exercise 9 - print out the shape of the array b.


In [220]:
print(my_b.shape)  # .shape is not a function; it's a property

(2, 3)


In [231]:
my_b.shape?  # this will open a docstring explaining

Exercise 10 - transpose the array b.


In [223]:
print(my_b.transpose())  # OR
print("\n")
print(my_b.T)

[[3 6]
 [4 7]
 [5 8]]


[[3 6]
 [4 7]
 [5 8]]


Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)


In [233]:
print(my_b.reshape(-1))  # if you don't know the length
print(my_b.reshape(6))
print(my_b.flatten())

[3 4 5 6 7 8]
[3 4 5 6 7 8]
[3 4 5 6 7 8]


Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)


In [232]:
print(my_b.reshape(6,1))  


[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


### Setup 3


In [120]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
my_c = np.array(c)

**HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.


Exercise 1 - Find the min, max, sum, and product of c.


In [132]:
min_c = my_c.min()
print("Min of array c = ", min_c)
max_c = my_c.max()
print("Max of array c = ", max_c)
sum_c = my_c.sum()
print("Sum of array c = ", sum_c)
prod_c = np.prod(my_c)      # OR my_c.prod()
print("Product of array c = ", prod_c)

Min of array c =  1
Max of array c =  9
Sum of array c =  45
Product of array c =  362880


Exercise 2 - Determine the standard deviation of c.


In [133]:
stdev_c = my_c.std()
print("Standard Dev of c =", stdev_c)

Standard Dev of c = 2.581988897471611


Exercise 3 - Determine the variance of c.


In [134]:
var_my_c = my_c.var()
print("Variance of array c = ", var_my_c)

Variance of array c =  6.666666666666667


Exercise 4 - Print out the shape of the array c


In [135]:
print("Shape of array c = ", my_c.shape)


Shape of array c =  (3, 3)


Exercise 5 - Transpose c and print out transposed result.


In [138]:
my_c_transposed = my_c.T
print("Transposed version of my_c: ")
print(my_c_transposed)

Transposed version of my_c: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Exercise 6 - Multiply c by the c-Transposed and print the result.


In [141]:
my_two_cs = my_c * my_c_transposed
print(my_two_cs)

[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]


Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [144]:
total_my_two_cs = my_two_cs.sum()
print(total_my_two_cs)

261


Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [234]:
#                           calling the function from the class itself
prod_my_c_my_c_transposed = np.prod(my_c) * np.prod(my_c_transposed)
# or                        my_c.prod() * my_c_transposed.prod()
#                           calling the method from the array object
print(prod_my_c_my_c_transposed)

print(my_two_cs.prod())   # Remember to use your own variables!!! 
                          #Make it easier on yourself!

131681894400
131681894400


### Setup 4


In [160]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
my_d = np.array(d)

Exercise 1 - Find the sine of all the numbers in d


In [161]:
sin_d = np.sin(my_d)
print(sin_d)

[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]


Exercise 2 - Find the cosine of all the numbers in d


In [162]:
cos_d = np.cos(my_d)
print(cos_d)

[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]


Exercise 3 - Find the tangent of all the numbers in d


In [163]:
tan_d = np.tan(my_d)
print(tan_d)

[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]


Exercise 4 - Find all the negative numbers in d


In [166]:
neg_d = my_d[my_d < 0]
print(neg_d)

[-90 -30 -45 -45]


Exercise 5 - Find all the positive numbers in d


In [167]:
pos_d = my_d[my_d > 0]
print(pos_d)

[ 90  30  45 120 180  45 270  90  60  45  90 180]


Exercise 6 - Return an array of only the unique numbers in d.


In [168]:
unique_my_d = np.unique(my_d)
print(unique_my_d)

[-90 -45 -30   0  30  45  60  90 120 180 270]


Exercise 7 - Determine how many unique numbers there are in d.


In [170]:
#This creates basically a frequency table of unique numbers in an array
unique_count_my_d = np.unique(my_d, return_counts=True)
print(unique_count_my_d)

(array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270]), array([1, 2, 1, 2, 1, 3, 1, 3, 1, 2, 1]))


Exercise 8 - Print out the shape of d.


In [174]:
print("The shape of my_d =", my_d.shape)

The shape of my_d = (3, 6)


Exercise 9 - Transpose and then print out the shape of d.


In [175]:
my_d.T

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

Exercise 10 - Reshape d into an array of 9 x 2


In [176]:
my_d.reshape((9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])